TP3_AFHBS/Models/Vehicule.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_AFHBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicule()
        {
            this.CommadeVehicules = new HashSet<CommadeVehicule>();
            this.Images = new HashSet<Image>();
            this.Options = new HashSet<Option>();
        }
    
        public int VehiculeID { get; set; }
        public string Type { get; set; }
        public string Marque { get; set; }
        public string Model { get; set; }
        public decimal PrixVente { get; set; }
        public Nullable<decimal> SoldePourcentage { get; set; }
        public bool IsNeuf { get; set; }
        public System.DateTime DateMiseEnVente { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommadeVehicule> CommadeVehicules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option> Options { get; set; }
    }
}

TP3_AFHBS/Controllers/CommadeVehiculesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP3_AFHBS.Controllers.ActionFilters;
using TP3_AFHBS.Models;

namespace TP3_AFHBS.Controllers
{
    public class CommadeVehiculesController : Controller
    {
        private TP3Entities db = new TP3Entities();

        // GET: CommadeVehicules
        [AdminOnly]
        public ActionResult Index()
        {
            var commadeVehicules = db.CommadeVehicules.Include(c => c.Commande).Include(c => c.Vehicule);
            return View(commadeVehicules.ToList());
        }

        // GET: CommadeVehicules/Details/5
        [SessionActiveOnly]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommadeVehicule commadeVehicule = db.CommadeVehicules.Find(id);

            
            if (commadeVehicule == null)
            {
                return HttpNotFound();
            }

            if ((string)Session[SessionVariables.Type] != UserTypes.Admin && (string)Session[SessionVariables.UserName] != commadeVehicule.Commande.UserName)
            {
                return new RedirectResult("~/Home/NotAuthorised");
            }

            ViewBag.VehiculeTitre = commadeVehicule.Vehicule.Marque + " " + commadeVehicule.Vehicule.Model;

            return View(commadeVehicule);
        }

        // GET: CommadeVehicules/Create
        [SessionActiveOnly]
        public ActionResult Create(int? id)
        {
            string UserName = (string)Session[SessionVariables.UserName];

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommadeVehicule cv = new CommadeVehicule();
            if ((string)Session[SessionVariables.Type] == UserTypes.Normal)
            {
                ViewBag.UserName = UserName;
            }
            else if ((string)Session[SessionVariables.Type] == UserTypes.Admin)
            {
                ViewBag.UserName = new SelectList(db.Users.Where(u => u.Type != UserTypes.Admin), "UserName", "UserName");
            }
            else if ((string)Session[SessionVariables.Type] == UserTypes.Societe)
            {
                ViewBag.UserName = UserName;
            }

            cv.Quantite = 1;
            cv.Vehicule = db.Vehicules.Find(id);
            cv.VehiculeID = id.Value;

            ViewBag.Options = new SelectList(db.Options.Where(o => o.VehiculeID == cv.VehiculeID), "OptionID", "Description");

            ViewBag.Prix = cv.Vehicule.SoldePourcentage == null ? cv.Vehicule.PrixVente : cv.Vehicule.PrixVente * ((100 - cv.Vehicule.SoldePourcentage) / 100);

            return View(cv);
        }

        // POST: CommadeVehicules/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [SessionActiveOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? VehiculeID, string UserName, int? Quantite, int[] Options)
        {
            CommadeVehicule cv = new CommadeVehicule();

            if ((string)Session[SessionVariables.Type] != UserTypes.Admin)
            {
                UserName = (string)Session[SessionVariables.UserName];
            }

            if (Quantite == null || VehiculeID == null || UserName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            { 
                Commande commande = db.Commandes.Where(c => c.UserName == UserName && c.Statut == CommandeStatuts.EnCours).FirstOrDefault();

                if (commande == null)
                {
                    commande = new Commande()
                    {
                        Date = DateTime.Now,
                        Statut = CommandeStatuts.EnCours,
                        UserName = UserName
                    };
                    db.Commandes.Add(commande);
                    db.SaveChanges();
                }

                cv.VehiculeID = VehiculeID.Value;

                cv.CommandeID = commande.CommandeID;

                cv.Quantite = Quantite;

                db.CommadeVehicules.Add(cv);
                db.SaveChanges();

                if (Options != null)
                {
                    foreach (int optionID in Options)
                    {
                        OptionCommande oc = new OptionCommande();

                        oc.OptionID = optionID;
                        oc.CommandeVehiculeID = cv.CommandeVehiculeID;

                        db.OptionCommandes.Add(oc);

                        db.SaveChanges();
                    }
                }
            }


            return View("Details", db.CommadeVehicules.Find(cv.CommandeVehiculeID));
        }

        // GET: CommadeVehicules/Edit/5
        [AdminOnly]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommadeVehicule commadeVehicule = db.CommadeVehicules.Find(id);
            if (commadeVehicule == null)
            {
                return HttpNotFound();
            }
            ViewBag.CommandeID = new SelectList(db.Commandes, "CommandeID", "Statut", commadeVehicule.CommandeID);
            ViewBag.VehiculeID = new SelectList(db.Vehicules, "VehiculeID", "Type", commadeVehicule.VehiculeID);
            return View(commadeVehicule);
        }

        // POST: CommadeVehicules/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [AdminOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommandeVehiculeID,VehiculeID,CommandeID")] CommadeVehicule commadeVehicule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(commadeVehicule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CommandeID = new SelectList(db.Commandes, "CommandeID", "Statut", commadeVehicule.CommandeID);
            ViewBag.VehiculeID = new SelectList(db.Vehicules, "VehiculeID", "Type", commadeVehicule.VehiculeID);
            return View(commadeVehicule);
        }

        // POST: CommadeVehicules/Delete/5
        [AdminOnly]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CommadeVehicule commadeVehicule = db.CommadeVehicules.Find(id);
            db.CommadeVehicules.Remove(commadeVehicule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TP3_AFHBS/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP3_AFHBS.Controllers.ActionFilters;
using TP3_AFHBS.Models;

namespace TP3_AFHBS.Controllers
{
    public class ImagesController : Controller
    {
        private TP3Entities db = new TP3Entities();

        // POST: Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [AdminOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ImageURL,VehiculeID")] Image image)
        {
            if (ModelState.IsValid)
            {
                db.Images.Add(image);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VehiculeID = new SelectList(db.Vehicules, "VehiculeID", "Type", image.VehiculeID);
            return View(image);
        }

        // POST: Images/Delete/5
        [AdminOnly]
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            Console.WriteLine(id);

            Image image = db.Images.Find(id);
            db.Images.Remove(image);
            db.SaveChanges();
            string message = "SUCCESS";
            return Json(new { Message = message, JsonRequestBehavior.AllowGet });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TP3_AFHBS/Controllers/VehiculesController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP3_AFHBS.Controllers.ActionFilters;
using TP3_AFHBS.Models;

namespace TP3_AFHBS.Controllers
{
    public class VehiculesController : Controller
    {
        private TP3Entities db = new TP3Entities();
        private IMapper mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Vehicule, VehiculeViewModel>();
            })
            .CreateMapper();

        // GET: Vehicules
        public ActionResult Index()
        {
            List<VehiculeViewModel> vehiculeVMs = new List<VehiculeViewModel>();

            foreach (Vehicule vehicule in db.Vehicules)
            {
                vehiculeVMs.Add(mapper.Map<Vehicule, VehiculeViewModel>(vehicule));
            }

            return View(vehiculeVMs);
        }

        [HttpPost]
        public ActionResult Index(bool? ImagePresent, string SearchTerm)
        {
            List<VehiculeViewModel> vehiculeVMs = new List<VehiculeViewModel>();

            List<Vehicule> vehicules = db.Vehicules.Where(v => ImagePresent.Value ? v.Images.Count > 0 : true && (v.Marque + v.Model + v.Description).Contains(SearchTerm)).ToList();

            foreach (Vehicule vehicule in vehicules)
            {
                vehiculeVMs.Add(mapper.Map<Vehicule, VehiculeViewModel>(vehicule));
            }

            return View(vehiculeVMs);
        }

        // GET: Vehicules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicule vehicule = db.Vehicules.Find(id);
            if (vehicule == null)
            {
                return HttpNotFound();
            }

            VehiculeViewModel vehiculeVM = mapper.Map<Vehicule, VehiculeViewModel>(vehicule);

            return View(vehiculeVM);
        }

        // GET: Vehicules/Create
        [AdminOnly]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehicules/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [AdminOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehiculeID,Type,Marque,Model,PrixVente,SoldePourcentage,IsNeuf,DateMiseEnVente,Description")] Vehicule vehicule)
        {
            if (ModelState.IsValid)
            {
                db.Vehicules.Add(vehicule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicule);
        }


        // GET: Vehicules/Edit/5
        [AdminOnly]
        [OutputCache(Duration = 0)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicule vehicule = db.Vehicules.Find(id);
            if (vehicule == null)
            {
                return HttpNotFound();
            }
            return View(vehicule);
        }

        // POST: Vehicules/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [AdminOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehiculeID,Type,Marque,Model,PrixVente,SoldePourcentage,IsNeuf,DateMiseEnVente,Description")] Vehicule vehicule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicule);
        }

        // GET: Vehicules/Delete/5
        [AdminOnly]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicule vehicule = db.Vehicules.Find(id);
            if (vehicule == null)
            {
                return HttpNotFound();
            }
            return View(vehicule);
        }

        // POST: Vehicules/Delete/5
        [AdminOnly]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicule vehicule = db.Vehicules.Find(id);
            db.Vehicules.Remove(vehicule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TP3_AFHBS/Views/Vehicules/Details.cshtml
@model TP3_AFHBS.Models.VehiculeViewModel

@{
    ViewBag.Title = "Détails";
}

<div>
    <p>

        @Html.ActionLink("Rétour au catalogue", "Index", null, new { @class = "btn btn-primary" })
    </p>



    <div class="row">
        <div class="col-md-6 text-left">
            <h4>@Html.DisplayFor(model => model.Marque) @Html.DisplayFor(model => model.Model)</h4>
        </div>
        <div class="col-md-6 text-right">
            @Html.ActionLink("Commander", "Create", "CommadeVehicules", new { id = Model.VehiculeID }, new { @class = "btn btn-success" })
        </div>
    </div>

    <hr />

    <div class="row mb-3">
        @foreach (TP3_AFHBS.Models.Image image in Model.Images)
        {
            <div class="col-md-4">
                <div class="card m-2 border-0">
                    <div class="card-img-caption">
                        <img class="card-img-top card-img-tp card-img-details" src="@image.ImageURL" />
                    </div>
                </div>
            </div>
        }
    </div>

    @if (Model.SoldePourcentage != null && Model.SoldePourcentage > 0)
    {
        <h2>
            <span class="badge badge-secondary"><del>$@Html.DisplayFor(modelItem => Model.PrixVente)</del></span>
            <span class="badge badge-success"><b>$@Html.DisplayFor(modelItem => Model.PrixAvecSolde)</b></span>
        </h2>
    }
    else
    {
        <h2>
            <span class="badge badge-primary">$@Html.DisplayFor(modelItem => Model.PrixVente)</span>
        </h2>
    }

    <div class="row">
        <div class="col-md-12">
            <h4 class="d-inline-block">
                @if (Model.IsNeuf)
                {
                    <span class="badge badge-info p-1">Nouveau!</span>
                }
                else
                {
                    <span class="badge badge-info p-1">Usagé</span>
                }
            </h4>

            <h4 class="d-inline-block">
                <span class="badge badge-info p-1">@Html.DisplayFor(model => model.DateMiseEnVente)</span>
            </h4>
        </div>
    </div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    <p>
        @if ((string)Session[TP3_AFHBS.Models.SessionVariables.Type] == TP3_AFHBS.Models.UserTypes.Admin)
        {
            <span>@Html.ActionLink("Edit", "Edit", new { id = Model.VehiculeID }, new { @class = "btn btn-primary" })</span>
        }
    </p>
</div>

TP3_AFHBS/Views/Vehicules/Edit.cshtml
@model TP3_AFHBS.Models.Vehicule

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" />
    </div>
}

<hr/>

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vehicule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VehiculeID)

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.Marque, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marque, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.PrixVente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrixVente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrixVente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.SoldePourcentage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoldePourcentage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoldePourcentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.IsNeuf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsNeuf)
                    @Html.ValidationMessageFor(model => model.IsNeuf, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.DateMiseEnVente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateMiseEnVente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateMiseEnVente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}

<hr />

<h3>Images</h3>

<div class="m-3 row">
    @foreach (TP3_AFHBS.Models.Image image in Model.Images)
    {

        <div id="IMG-@image.ImageID" class="col-md-4 d-flex flex-column justify-content-center mb-3">
            <img src=@image.ImageURL class="vehicule-image-edit w-100 h-auto mb-2" />
            <button class="btn btn-danger mt-auto" onclick="deleteImage(@image.ImageID)">Supprimer</button>
        </div>
    }
    <div class="col-md-4 w-100 h-100">
        <input id="dataImageURL" class="form-control w-100 mb-2 mw-100" placeholder="@Html.DisplayNameFor(x => x.Images.FirstOrDefault().ImageURL)" />
        <button id="btnAddImage" class="btn btn-success w-100">Ajouter</button>
    </div>
</div>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    function deleteImage(id) {
        console.log(id);
        $.ajax({
            type: "POST",
            url: '@Url.Action("Delete", "Images")',
            data: '{id: ' + id + "}",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function () {
                $("#IMG-" + id).remove();
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(xhr.status);
                alert(xhr.responseText);
            }
        });
    }

    function ajoutImage() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Images")',
            data: '{ImageURL: "' + $("#btnAddImage") + '", VehiculeID : @Model.VehiculeID}',
            dataType: 'json',
            contentType: "application/json; charset=utf-8",
            error: function (xhr, ajaxOptions, thrownError) {
                alert(xhr.status);
                alert(xhr.responseText);
            }
        })
    }
</script>

TP3_AFHBS/Views/Vehicules/Index.cshtml
@model IEnumerable<TP3_AFHBS.Models.VehiculeViewModel>

@{
    ViewBag.Title = "Catalogue";
}

<h2 class="mb-3">Nos Vehicules</h2>

@if ((string)Session[TP3_AFHBS.Models.SessionVariables.Type] == TP3_AFHBS.Models.UserTypes.Admin)
{
    <p>
        @Html.ActionLink("Ajouter", "Create")
    </p>
}

<div class="jumbotron py-3">
    <h4>Recherche</h4>
    @using (Html.BeginForm("Index", "Vehicules", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-check my-2">
            <input class="form-check-input" id="imagePresent" name="ImagePresent" type="checkbox" />
            <label class="form-check-label" for="imagePresent">Seulement avec une image</label>
        </div>

        <div class="form-group">
            <input class="form-control" name="SearchTerm" type="text" placeholder="Recherche..." />
        </div>
        <div class="form-group mb-2">
            <input type="submit" value="Search" class="btn btn-secondary" />
        </div>
    }
</div>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="card w-100 my-2">
                <div class="card-img-caption">
                    <div class="card-text card-img-tp d-flex align-items-center justify-content-center"></div>
                    <p class="caption-text">@item.Marque @item.Model</p>
                    @if (item.Images.FirstOrDefault() == null)
                    {
                        <img class="card-img-top card-img-tp" src="" />
                    }
                    else
                    {
                        <img class="card-img-top card-img-tp" src="@item.Images.FirstOrDefault().ImageURL" />
                    }
                </div>

                <div class="card-body">
                    @if (item.SoldePourcentage != null && item.SoldePourcentage > 0)
                    {
                        <h2>
                            <span class="badge badge-secondary"><del>$@Html.DisplayFor(modelItem => item.PrixVente)</del></span>
                            <span class="badge badge-success"><b>$@Html.DisplayFor(modelItem => item.PrixAvecSolde)</b></span>
                        </h2>
                    }
                    else
                    {
                        <h2>
                            <span class="badge badge-primary">$@Html.DisplayFor(modelItem => item.PrixVente)</span>
                        </h2>
                    }

                    <div class="row">
                        <div class="col-md-12 text-left">
                            @if (item.IsNeuf)
                            {
                                <span class="badge badge-info p-1">Nouveau!</span>
                            }
                            else
                            {
                                <span class="badge badge-info p-1">Usagé</span>
                            }
                            <span class="badge badge-info p-1">@Html.DisplayFor(modelItem => item.DateMiseEnVente)</span>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Détails", "Details", "Vehicules", new { id = item.VehiculeID }, new { @class = "btn btn-secondary float-right" })
                </div>
            </div>
        </div>
    }
</div>