TP3_AFHBS/Models/Commande.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_AFHBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.CommadeVehicules = new HashSet<CommadeVehicule>();
        }
    
        public int CommandeID { get; set; }
        public System.DateTime Date { get; set; }
        public string Statut { get; set; }
        public string UserName { get; set; }
        public string ModePaiement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommadeVehicule> CommadeVehicules { get; set; }
        public virtual User User { get; set; }
    }
}

TP3_AFHBS/Controllers/CommandesController.cs
using IronPdf;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP3_AFHBS.Controllers.ActionFilters;
using TP3_AFHBS.Models;
using TP3_AFHBS.Models.Libraries;

namespace TP3_AFHBS.Controllers
{
    public class CommandesController : Controller
    {
        private TP3Entities db = new TP3Entities();


        // GET: Commandes
        [SessionActiveOnly]
        public ActionResult Index()
        {
            if ((string)Session[SessionVariables.Type] == UserTypes.Admin)
            {
                var commandes = db.Commandes.Include(c => c.User);
                return View(commandes.ToList());
            }
            else
            {
                string userName = (string)Session[SessionVariables.UserName];

                var commandes = db.Commandes.Where(c => c.UserName == userName);
                return View(commandes.ToList());
            }
        }

        // GET: Commandes/Details/5
        [SessionActiveOnly]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commande commande = db.Commandes.Find(id);

            if ((string)Session[SessionVariables.Type] != UserTypes.Admin && (string)Session[SessionVariables.UserName] != commande.UserName)
            {
                return new RedirectResult("~/Home/NotAuthorised");
            }
            if (commande == null)
            {
                return HttpNotFound();
            }
            return View(commande);
        }
        // GET: Commandes/Edit/5
        [SessionActiveOnly]
        [AdminOnly]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commande commande = db.Commandes.Find(id);

            if ((string)Session[SessionVariables.Type] != UserTypes.Admin && (string)Session[SessionVariables.UserName] != commande.UserName)
            {
                return new RedirectResult("~/Home/NotAuthorised");
            }
            if (commande == null)
            {
                return HttpNotFound();
            }
            //Créer la liste à afficher dans le DropDownList des statuts
            List<string> listStatus = new List<string>();
            foreach (string st in CommandeStatuts.Display.Keys)
            {
                listStatus.Add(st);
            }

            List<string> modePaiements = new List<string>();

            modePaiements.Add(null);

            foreach (string mp in ModesPaiement.Display.Keys)
            {
                modePaiements.Add(mp);
            }


            ViewBag.ModePaiement = new SelectList(modePaiements);

            ViewBag.Statut = new SelectList(listStatus);

            return View(commande);
        }
        
        // POST: Commandes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [SessionActiveOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommandeID,Date,Statut,UserName,ModePaiement")] Commande commande)
        {
            if (ModelState.IsValid)
            {
                Commande com = db.Commandes.Find(commande.CommandeID);
                com.Statut = commande.Statut;
                com.ModePaiement = commande.ModePaiement;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserName = new SelectList(db.Users, "UserName", "MdpHash", commande.UserName);
            return View(commande);
        }

        public ActionResult Finalise(int id)
        {
            Commande commande = db.Commandes.Find(id);

            return View(commande);
        }

        [HttpPost]
        [ValidateInput(false)]
        public FileResult PrintDOC(string BDCContent)
        {

            HtmlToPdf renderer = new IronPdf.HtmlToPdf();
            byte[] pdf = renderer.RenderHtmlAsPdf(BDCContent).BinaryData;

            return File(pdf, "application/pdf", "document-" + DateTime.Now.Date + ".pdf");


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TP3_AFHBS/Views/Commandes/Details.cshtml
@model TP3_AFHBS.Models.Commande

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Commande</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>

<div class="row">
    @foreach (var cv in Model.CommadeVehicules)
    {
        <div class="col-md-4">
            <div class="card w-100 my-2">
                <div class="card-img-caption">
                    <div class="card-text card-img-tp d-flex align-items-center justify-content-center"></div>
                    <p class="caption-text">@cv.Vehicule.Marque @cv.Vehicule.Model</p>
                    @if (cv.Vehicule.Images.FirstOrDefault() == null)
                    {
                        <img class="card-img-top card-img-tp" src="" />
                    }
                    else
                    {
                        <img class="card-img-top card-img-tp" src="@cv.Vehicule.Images.FirstOrDefault().ImageURL" />
                    }
                </div>

                <div class="card-body d-flex flex-wrap">
                    <span class="badge badge-info m-1 p-1">
                        $@{
                            var result = String.Format("{0:0.00}", (cv.Vehicule.PrixVente * (cv.Vehicule.SoldePourcentage == null ? 1 : (100 - cv.Vehicule.SoldePourcentage.Value) / 100)));
                            <span>@result</span>
                        }
                    </span>
                    <span class="badge badge-info m-1 p-1">Quantite: @cv.Quantite</span>
                    @foreach (var opt in cv.OptionCommandes)
                    {
                        <span class="badge badge-info m-1 p-1">@opt.Option.Description</span>
                    }

                </div>

            </div>
        </div>
    }
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

TP3_AFHBS/Views/Commandes/Edit.cshtml
@model TP3_AFHBS.Models.Commande

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Commande</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CommandeID)


        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.CommandeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.CommandeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CommandeID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="mb-2">
                    @Html.DisplayFor(model => model.Statut)
                </div>
                @Html.DropDownList("Statut", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="d-flex justify-content-start mt-2">
            @Html.LabelFor(model => model.ModePaiement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="mb-2">
                    @Html.DisplayFor(model => model.ModePaiement)
                </div>
                @Html.DropDownList("ModePaiement", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModePaiement, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </div>

    </div>
}

<div class="row">
    @foreach (var cv in Model.CommadeVehicules)
    {
        <div class="col-md-4">
            <div class="card w-100 my-2">
                <div class="card-img-caption">
                    <div class="card-text card-img-tp d-flex align-items-center justify-content-center"></div>
                    <p class="caption-text">@cv.Vehicule.Marque @cv.Vehicule.Model</p>
                    @if (cv.Vehicule.Images.FirstOrDefault() == null)
                    {
                        <img class="card-img-top card-img-tp" src="" />
                    }
                    else
                    {
                        <img class="card-img-top card-img-tp" src="@cv.Vehicule.Images.FirstOrDefault().ImageURL" />
                    }
                </div>

                <div class="card-body d-flex flex-wrap">
                    <span class="badge badge-info m-1 p-1">
                        $@{
                            var result = String.Format("{0:0.00}", (cv.Vehicule.PrixVente * (cv.Vehicule.SoldePourcentage == null ? 1 : (100 - cv.Vehicule.SoldePourcentage.Value) / 100)));
                            <span>@result</span>
                        }
                    </span>
                    <span class="badge badge-info m-1 p-1">Quantite: @cv.Quantite</span>
                    @foreach (var opt in cv.OptionCommandes)
                    {
                        <span class="badge badge-info m-1 p-1">@opt.Option.Description</span>
                    }

                </div>

            </div>
        </div>
    }
</div>

<div>
    @Html.ActionLink("Generer documents", "Finalise", new { id = Model.CommandeID }, new { @class = "btn btn-secondary" })
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TP3_AFHBS/Views/Commandes/Finalise.cshtml
@model TP3_AFHBS.Models.Commande

@{
    ViewBag.Title = "Documents";
}

<h2>Documents</h2>

<div>
    <h4>Commande</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

    </dl>
</div>

<hr />

<h3>Documents</h3>

<div id="bonCommPDF" class="m-3 border border-secondary">
    <div class="p-3">
        <h2>Bon de Commande</h2>

        <hr />

        <div>
            <h4>@Model.User.Nom</h4>
            <span>@Model.User.Email</span>
        </div>


        <hr />

        <table class="table">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Voiture
                    </th>
                    <th>
                        Quantité
                    </th>
                    <th>
                        Options
                    </th>
                    <th>
                        Prix
                    </th>
                    <th>
                        Solde
                    </th>
                    <th>
                        Prix final
                    </th>
                </tr>
            </thead>

            @{
                int i = 0;
                decimal total = 0;
                <tbody>

                    @foreach (var cv in Model.CommadeVehicules)
                    {
                        i = i + 1;
                        <tr>
                            <td>
                                @i
                            </td>
                            <td>
                                @cv.Vehicule.Marque @cv.Vehicule.Model
                            </td>
                            <td>
                                @cv.Quantite
                            </td>
                            <td>
                                @foreach (var opt in cv.OptionCommandes)
                                {
                                    <span class="badge badge-info m-1 p-1">@opt.Option.Description</span>
                                }
                            </td>
                            <td>
                                $@cv.Vehicule.PrixVente
                            </td>
                            <td>
                                @{
                                    var solde = cv.Vehicule.SoldePourcentage == null ? "" : cv.Vehicule.SoldePourcentage + "%";
                                    <span>@solde</span>
                                }
                            </td>
                            <td>
                                $@{
                                    var result = (cv.Vehicule.PrixVente * (cv.Vehicule.SoldePourcentage == null ? 1 : (100 - cv.Vehicule.SoldePourcentage.Value) / 100));
                                    total = total + result;
                                    <span>@String.Format("{0:0.00}", result)</span>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th>
                            Total:
                        </th>
                        <td>
                            $@String.Format("{0:0.00}", total)
                        </td>
                    </tr>
                </tfoot>
            }
        </table>
    </div>
</div>

@using (Html.BeginForm("PrintDOC", "Commandes", FormMethod.Post))
{
    <input type="hidden" name="BDCContent" />
    <input type="submit" value="Télécharger le document" class="btn btn-success" onclick="printBDC()" />
}

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CommandeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<script>
    function printBDC() {
        console.log("printDoc");
        document.querySelector("input[name='BDCContent']").value = document.querySelector("#bonCommPDF").innerHTML;
        console.log(document.querySelector("input[name='BDCContent']").value);
    }
</script>

TP3_AFHBS/Views/Commandes/Index.cshtml
@model IEnumerable<TP3_AFHBS.Models.Commande>

@{
    ViewBag.Title = "Commandes";
}

<h2>Commandes</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CommandeID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Statut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CommandeID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Statut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @if ((string)Session[TP3_AFHBS.Models.SessionVariables.Type] == TP3_AFHBS.Models.UserTypes.Admin)
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.CommandeID }) <span>|</span>
                }
                @Html.ActionLink("Details", "Details", new { id = item.CommandeID })
            </td>
        </tr>
    }

</table>

TP3_AFHBS/Views/Commandes/ViewImageVehicule.cshtml
@model TP3_AFHBS.Models.Image


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ImageID)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehiculeID, "VehiculeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehiculeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehiculeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}